import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  English: {
    home: "Home",
    result: "AI Result",
    appointment: "Appointment",
    medicines: "Medicines",
    symptoms_checker: "NabhaCure - Symptoms Checker",
    describe_symptoms: "Describe your symptoms below to get instant AI advice.",
    select_language: "Select Language:",
    how_feeling: "How are you feeling?",
    placeholder_symptoms: "Describe your symptoms (e.g., I have a headache and fever)...",
    voice_input: "Voice Input",
    analyze: "Analyze Symptoms",
    ai_results: "AI Analysis Results",
    symptoms_provided: "Symptoms Provided:",
    lang_selected: "Language Selected:",
    urgency: "Urgency Level:",
    advice: "AI Advice:",
    analyzed_on: "Analyzed on:",
    book_appointment: "Book Appointment",
    view_medicines: "View Recommended Medicines",
    start_new: "Start New Analysis",
    book_title: "Book an Appointment",
    book_desc: "Fill in the form below to book a consultation with our experts.",
    full_name: "Full Name:",
    phone_number: "Phone Number:",
    pref_date: "Preferred Date:",
    pref_time: "Preferred Time:",
    specialty: "Specialty:",
    book_my: "Book My Appointment",
    confirmed: "Booking Confirmed!",
    confirmed_desc: "Your appointment has been successfully scheduled. We will contact you soon.",
    book_another: "Book Another",
    essential_meds: "Essential Medicines",
    meds_desc: "A list of commonly used medicines. Always consult a doctor before use.",
    search_meds: "Search for medicine (e.g., Pain, Fever)...",
    dosage: "Typical Dosage:",
    location: "Location:",
    pharmacy: "Pharmacy:",
    distance: "Distance:",
    km: "km away",
    note: "Note:",
    note_desc: "This list is for informational purposes only. Do not self-medicate for serious conditions.",
    no_results: "No Results Found",
    go_home: "Go back Home",
    join_call: "Join Video Call",
    call_doctor: "Consult Doctor via Video",
    doctor_waiting: "Doctor is waiting for you!",
    end_call: "End Consultation",
    audio_call: "Audio Call",
    emergency_call: "Emergency Call",
    appointment_fee: "Appointment Fee:",
    available_time: "Available Time:",
    select_doctor: "Select Doctor:",
    specialization: "Specialization:"
  },
  Hindi: {
    home: "होम",
    result: "AI परिणाम",
    appointment: "अपॉइंटमेंट",
    medicines: "दवाइयां",
    symptoms_checker: "नाभाक्योर - लक्षणों की जांच",
    describe_symptoms: "तुरंत AI सलाह पाने के लिए नीचे अपने लक्षणों का वर्णन करें।",
    select_language: "भाषा चुनें:",
    how_feeling: "आप कैसा महसूस कर रहे हैं?",
    placeholder_symptoms: "अपने लक्षणों का वर्णन करें (जैसे, मुझे सिरदर्द और बुखार है)...",
    voice_input: "आवाज से इनपुट",
    analyze: "लक्षणों का विश्लेषण करें",
    ai_results: "AI विश्लेषण परिणाम",
    symptoms_provided: "दिए गए लक्षण:",
    lang_selected: "चुनी गई भाषा:",
    urgency: "तत्परता स्तर:",
    advice: "AI सलाह:",
    analyzed_on: "विश्लेषण का समय:",
    book_appointment: "अपॉइंटमेंट बुक करें",
    view_medicines: "अनुशंसित दवाइयां देखें",
    start_new: "नया विश्लेषण शुरू करें",
    book_title: "अपॉइंटमेंट बुक करें",
    book_desc: "हमारे विशेषज्ञों के साथ परामर्श बुक करने के लिए नीचे दिया गया फॉर्म भरें।",
    full_name: "पूरा नाम:",
    phone_number: "फ़ोन नंबर:",
    pref_date: "पसंद की तारीख:",
    pref_time: "पसंद का समय:",
    specialty: "विशेषज्ञता:",
    book_my: "मेरा अपॉइंटमेंट बुक करें",
    confirmed: "बुकिंग की पुष्टि हो गई!",
    confirmed_desc: "आपका अपॉइंटमेंट सफलतापूर्वक शेड्यूल हो गया है। हम जल्द ही आपसे संपर्क करेंगे।",
    book_another: "दूसरा बुक करें",
    essential_meds: "आवश्यक दवाइयां",
    meds_desc: "आमतौर पर इस्तेमाल की जाने वाली दवाओं की सूची। उपयोग करने से पहले हमेशा डॉक्टर से सलाह लें।",
    search_meds: "दवा खोजें (जैसे, दर्द, बुखार)...",
    dosage: "सामान्य खुराक:",
    location: "स्थान:",
    pharmacy: "फार्मेसी:",
    distance: "दूरी:",
    km: "किमी दूर",
    note: "नोट:",
    note_desc: "यह सूची केवल सूचनात्मक उद्देश्यों के लिए है। गंभीर स्थितियों के लिए स्वयं दवा न लें।",
    no_results: "कोई परिणाम नहीं मिला",
    go_home: "होम पर वापस जाएं",
    join_call: "वीडियो कॉल से जुड़ें",
    call_doctor: "वीडियो द्वारा डॉक्टर से परामर्श करें",
    doctor_waiting: "डॉक्टर आपका इंतज़ार कर रहे हैं!",
    end_call: "परामर्श समाप्त करें",
    audio_call: "ऑडियो कॉल",
    emergency_call: "आपातकालीन कॉल",
    appointment_fee: "परामर्श शुल्क:",
    available_time: "उपलब्ध समय:",
    select_doctor: "डॉक्टर चुनें:",
    specialization: "विशेषज्ञता:"
  },
  Punjabi: {
    home: "ਹੋਮ",
    result: "AI ਨਤੀਜਾ",
    appointment: "ਅਪੌਇੰਟਮੈਂਟ",
    medicines: "ਦਵਾਈਆਂ",
    symptoms_checker: "ਨਾਭਾਕਿਓਰ - ਲੱਛਣਾਂ ਦੀ ਜਾਂਚ",
    describe_symptoms: "ਤੁਰੰਤ AI ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਹੇਠਾਂ ਆਪਣੇ ਲੱਛਣਾਂ ਦਾ ਵਰਣਨ ਕਰੋ।",
    select_language: "ਭਾਸ਼ਾ ਚੁਣੋ:",
    how_feeling: "ਤੁਸੀਂ ਕਿਵੇਂ ਮਹਿਸੂਸ ਕਰ ਰਹੇ ਹੋ?",
    placeholder_symptoms: "ਆਪਣੇ ਲੱਛਣਾਂ ਦਾ ਵਰਣਨ ਕਰੋ (ਜਿਵੇਂ ਕਿ, ਮੈਨੂੰ ਸਿਰਦਰਦ ਅਤੇ ਬੁਖਾਰ ਹੈ)...",
    voice_input: "ਆਵਾਜ਼ ਇਨਪੁਟ",
    analyze: "ਲੱਛਣਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    ai_results: "AI ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜੇ",
    symptoms_provided: "ਦਿੱਤੇ ਗਏ ਲੱਛਣ:",
    lang_selected: "ਚੁਣੀ ਗਈ ਭਾਸ਼ਾ:",
    urgency: "ਜ਼ਰੂਰਤ ਦਾ ਪੱਧਰ:",
    advice: "AI ਸਲਾਹ:",
    analyzed_on: "ਵਿਸ਼ਲੇਸ਼ਣ ਦਾ ਸਮਾਂ:",
    book_appointment: "ਅਪੌਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ",
    view_medicines: "ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਦਵਾਈਆਂ ਦੇਖੋ",
    start_new: "ਨਵਾਂ ਵਿਸ਼ਲੇਸ਼ਣ ਸ਼ੁਰੂ ਕਰੋ",
    book_title: "ਅਪੌਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ",
    book_desc: "ਸਾਡੇ ਮਾਹਰਾਂ ਨਾਲ ਸਲਾਹ-ਮਸ਼ਵਰਾ ਬੁੱਕ ਕਰਨ ਲਈ ਹੇਠਾਂ ਦਿੱਤਾ ਫਾਰਮ ਭਰੋ।",
    full_name: "ਪੂਰਾ ਨਾਮ:",
    phone_number: "ਫੋਨ ਨੰਬਰ:",
    pref_date: "ਪਸੰਦੀਦਾ ਤਾਰੀਖ:",
    pref_time: "ਪਸੰਦੀਦਾ ਸਮਾਂ:",
    specialty: "ਮਹਾਰਤ:",
    book_my: "ਮੇਰੀ ਅਪੌਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ",
    confirmed: "ਬੁਕਿੰਗ ਦੀ ਪੁਸ਼ਟੀ ਹੋ ਗਈ!",
    confirmed_desc: "ਤੁਹਾਡੀ ਅਪੌਇੰਟਮੈਂਟ ਸਫਲਤਾਪੂਰਵਕ ਤਹਿ ਕੀਤੀ ਗਈ ਹੈ। ਅਸੀਂ ਜਲਦੀ ਹੀ ਤੁਹਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰਾਂਗੇ।",
    book_another: "ਹੋਰ ਬੁੱਕ ਕਰੋ",
    essential_meds: "ਜ਼ਰੂਰੀ ਦਵਾਈਆਂ",
    meds_desc: "ਆਮ ਤੌਰ 'ਤੇ ਵਰਤੀਆਂ ਜਾਣ ਵਾਲੀਆਂ ਦਵਾਈਆਂ ਦੀ ਸੂਚੀ। ਵਰਤਣ ਤੋਂ ਪਹਿਲਾਂ ਹਮੇਸ਼ਾਂ ਡਾਕਟਰ ਦੀ ਸਲਾਹ ਲਓ।",
    search_meds: "ਦਵਾਈ ਲੱਭੋ (ਜਿਵੇਂ ਕਿ, ਦਰਦ, ਬੁਖਾਰ)...",
    dosage: "ਆਮ ਖ਼ੁਰਾਕ:",
    location: "ਸਥਾਨ:",
    pharmacy: "ਫਾਰਮੇਸੀ:",
    distance: "ਦੂਰੀ:",
    km: "ਕਿਲੋਮੀਟਰ ਦੂਰ",
    note: "ਨੋਟ:",
    note_desc: "ਇਹ ਸੂਚੀ ਸਿਰਫ ਜਾਣਕਾਰੀ ਦੇ ਉਦੇਸ਼ਾਂ ਲਈ ਹੈ। ਗੰਭੀਰ ਸਥਿਤੀਆਂ ਲਈ ਆਪਣੇ ਆਪ ਦਵਾਈ ਨਾ ਲਓ।",
    no_results: "ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ ਮਿਲਿਆ",
    go_home: "ਹੋਮ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    join_call: "ਵੀਡੀਓ ਕਾਲ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ",
    call_doctor: "ਵੀਡੀਓ ਰਾਹੀਂ ਡਾਕਟਰ ਨਾਲ ਸਲਾਹ ਕਰੋ",
    doctor_waiting: "ਡਾਕਟਰ ਤੁਹਾਡਾ ਇੰਤਜ਼ਾਰ ਕਰ ਰਹੇ ਹਨ!",
    end_call: "ਸਲਾਹ-ਮਸ਼ਵਰਾ ਖਤਮ ਕਰੋ",
    audio_call: "ਆਡੀਓ ਕਾਲ",
    emergency_call: "ਐਮਰਜੈਂਸੀ ਕਾਲ",
    appointment_fee: "ਅਪੌਇੰਟਮੈਂਟ ਫੀਸ:",
    available_time: "ਉਪਲਬਧ ਸਮਾਂ:",
    select_doctor: "ਡਾਕਟਰ ਚੁਣੋ:",
    specialization: "ਮਹਾਰਤ:"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('nabhacure_lang') || 'English');

  const changeLanguage = (newLang) => {
    setLanguage(newLang);
    localStorage.setItem('nabhacure_lang', newLang);
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
